config/routes.rb
Clube::Application.routes.draw do

  resources :profile_images

  resources :qualifications

  devise_for :users,:controllers => {:registrations => "registrations"}
  resources :users do
    collection do
      get 'profile'
    end
  end

  root "home#index"

  

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/famailyinfo.rb
class Famailyinfo < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user


end

app/models/profile_image.rb
class ProfileImage < ActiveRecord::Base
  belongs_to :user

  mount_uploader :image, ImageUploader
end

app/models/qualification.rb
class Qualification < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_one :famailyinfo
  has_many :addresses
  has_many :profile_images
  accepts_nested_attributes_for :profile
  accepts_nested_attributes_for :famailyinfo
  accepts_nested_attributes_for :addresses
  accepts_nested_attributes_for :profile_images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  def layout_by_resource
    if devise_controller? && resource_name == :user
      "devise_layout"
    else
      "application"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profile_images_controller.rb
class ProfileImagesController < ApplicationController
  before_action :set_profile_image, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @profile_images = ProfileImage.all
    respond_with(@profile_images)
  end

  def show
    respond_with(@profile_image)
  end

  def new
    @profile_image = ProfileImage.new
    respond_with(@profile_image)
  end

  def edit
  end

  def create
    @profile_image = ProfileImage.new(profile_image_params)
    @profile_image.save
    respond_with(@profile_image)
  end

  def update
    @profile_image.update(profile_image_params)
    respond_with(@profile_image)
  end

  def destroy
    @profile_image.destroy
    respond_with(@profile_image)
  end

  private
    def set_profile_image
      @profile_image = ProfileImage.find(params[:id])
    end

    def profile_image_params
      params.require(:profile_image).permit(:image)
    end
end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  before_action :set_qualification, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @qualifications = Qualification.all
    respond_with(@qualifications)
  end

  def show
    respond_with(@qualification)
  end

  def new
    @qualification = Qualification.new
    respond_with(@qualification)
  end

  def edit
  end

  def create
    @qualification = Qualification.new(qualification_params)
    @qualification.save
    respond_with(@qualification)
  end

  def update
    @qualification.update(qualification_params)
    respond_with(@qualification)
  end

  def destroy
    @qualification.destroy
    respond_with(@qualification)
  end

  private
    def set_qualification
      @qualification = Qualification.find(params[:id])
    end

    def qualification_params
      params.require(:qualification).permit(:name)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def edit
    @user = User.find(current_user.id)
    if @user.profile.nil? || @user.profile.blank?
      @user.profile.build
    end
    if @user.famailyinfo.nil? || @user.famailyinfo.blank?
      @user.famailyinfo.build
    end
    if @user.addresses.nil? || @user.addresses.blank?
      1.times { @user.addresses.build }
    end
    if @user.profile_images.nil? || @user.profile_images.blank?
      5.times { @user.profile_images.build }
    end
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to "/"
    else
      render :action => 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password,
    profile_attributes: [:id,:first_name, :last_name,:contact1,:contact2,:date_of_birth,:gender,:education],
    profile_images_attributes: [:id,:image],
    famailyinfo_attributes: [:id,:father_name,:monther,:father_occupation,:mother_occupation,:income,:no_of_sister,:no_of_brother,:contact1,:contact2],
    addresses_attributes: [:id,:address1,:address2,:city,:state,:country,:zip_code])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def profile
    #@user = User.find_by_id(current_user.id)
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_images_helper.rb
module ProfileImagesHelper
end

app/helpers/qualifications_helper.rb
module QualificationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def get_qualification(id)
    @qualification = Qualification.find(id)
    return @qualification.name
  end
end

app/views/component/_date_field.html.erb
<div class="form-group">
  <label><%= label_val %></label>
  <%= f.date_field n ,:class=>"form-control input-sm" %>
</div>

app/views/component/_image_slider.html.erb
<script>
    jssor_1_slider_init = function() {

        var jssor_1_options = {
            $AutoPlay: false,
            $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
            },
            $ThumbnailNavigatorOptions: {
                $Class: $JssorThumbnailNavigator$,
                $Cols: 9,
                $SpacingX: 3,
                $SpacingY: 3,
                $Align: 260
            }
        };

        var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

        //responsive code begin
        //you can remove responsive code if you don't want the slider scales while window resizing
        function ScaleSlider() {
            var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
            if (refSize) {
                refSize = Math.min(refSize, 600);
                jssor_1_slider.$ScaleWidth(refSize);
            }
            else {
                window.setTimeout(ScaleSlider, 30);
            }
        }
        ScaleSlider();
        $Jssor$.$AddEvent(window, "load", ScaleSlider);
        $Jssor$.$AddEvent(window, "resize", ScaleSlider);
        $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
        //responsive code end
    };
</script>

<style>

    /* jssor slider arrow navigator skin 02 css */
    /*
    .jssora02l                  (normal)
    .jssora02r                  (normal)
    .jssora02l:hover            (normal mouseover)
    .jssora02r:hover            (normal mouseover)
    .jssora02l.jssora02ldn      (mousedown)
    .jssora02r.jssora02rdn      (mousedown)
    */
    .jssora02l, .jssora02r {
        display: block;
        position: absolute;
        /* size of arrow element */
        width: 55px;
        height: 55px;
        cursor: pointer;
        background: url('/assets/slider/a02.png') no-repeat;
        overflow: hidden;
    }
    .jssora02l { background-position: -3px -33px; }
    .jssora02r { background-position: -63px -33px; }
    .jssora02l:hover { background-position: -123px -33px; }
    .jssora02r:hover { background-position: -183px -33px; }
    .jssora02l.jssora02ldn { background-position: -3px -33px; }
    .jssora02r.jssora02rdn { background-position: -63px -33px; }

    /* jssor slider thumbnail navigator skin 03 css */
    /*
    .jssort03 .p            (normal)
    .jssort03 .p:hover      (normal mouseover)
    .jssort03 .pav          (active)
    .jssort03 .pdn          (mousedown)
    */

    .jssort03 .p {
        position: absolute;
        top: 0;
        left: 0;
        width: 100px;
        height: 82px;
    }

    .jssort03 .t {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        border: none;
    }

    .jssort03 .w, .jssort03 .pav:hover .w {
        position: absolute;
        width: 60px;
        height: 100px;
        border: white 1px dashed;
        box-sizing: content-box;
    }

    .jssort03 .pdn .w, .jssort03 .pav .w {
        border-style: solid;
    }

    .jssort03 .c {
        position: absolute;
        top: 0;
        left: 0;
        width: 62px;
        height: 62px;
        background-color: #000;

        filter: alpha(opacity=45);
        opacity: .45;
        transition: opacity .6s;
        -moz-transition: opacity .6s;
        -webkit-transition: opacity .6s;
        -o-transition: opacity .6s;
    }

    .jssort03 .p:hover .c, .jssort03 .pav .c {
        filter: alpha(opacity=0);
        opacity: 0;
    }

    .jssort03 .p:hover .c {
        transition: none;
        -moz-transition: none;
        -webkit-transition: none;
        -o-transition: none;
    }

    * html .jssort03 .w {
        width /**/: 62px;
        height /**/: 32px;
    }

</style>
<div class="col-sm-8">
<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 600px; height: 550px; overflow: hidden; visibility: hidden;">
  <!-- Loading Screen -->
  <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
    <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
    <div style="position:absolute;display:block;background:url('/assets/slider/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
  </div>
  <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 600px; height: 500px; overflow: hidden;">
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/assets/slider/002.jpg" />
      <img data-u="thumb" src="/assets/slider/thumb-002.jpg" />
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/assets/slider/003.jpg" />
      <img data-u="thumb" src="/assets/slider/thumb-003.jpg" />
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/assets/slider/004.jpg" />
      <img data-u="thumb" src="/assets/slider/thumb-004.jpg" />
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/assets/slider/005.jpg" />
      <img data-u="thumb" src="/assets/slider/thumb-005.jpg" />
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="img/006.jpg" />
      <img data-u="thumb" src="img/thumb-006.jpg" />
    </div>
  </div>
  <!-- Thumbnail Navigator -->
  <div u="thumbnavigator" class="jssort03" style="position:absolute;left:0px;bottom:0px;width:600px;height:60px;" data-autocenter="1">
    <div style="position: absolute; top: 0; left: 0; width: 100%; height:100%; background-color: #000; filter:alpha(opacity=30.0); opacity:0.3;"></div>
    <!-- Thumbnail Item Skin Begin -->
    <div u="slides" style="cursor: default;">
      <div u="prototype" class="p">
        <div class="w">
          <div u="thumbnailtemplate" class="t"></div>
        </div>
        <div class="c"></div>
      </div>
    </div>
    <!-- Thumbnail Item Skin End -->
  </div>
  <!-- Arrow Navigator -->
  <span data-u="arrowleft" class="jssora02l" style="top:0px;left:8px;width:55px;height:55px;" data-autocenter="2"></span>
  <span data-u="arrowright" class="jssora02r" style="top:0px;right:8px;width:55px;height:55px;" data-autocenter="2"></span>
</div>

</div>

app/views/component/_menu.html.erb
<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
  <div class="container-fluid">
    <div class="navbar-header"><a class="navbar-brand" href="#">Camp</a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse navbar-menubuilder">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">Home</a></li>
        <% if !user_signed_in? %>
            <li>
              <%= link_to "Register", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "Login", new_user_session_path %>
            </li>
        <% end %>
        <li><a href="#">Plan</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#" class="active">Contact</a></li>
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Profile", profile_users_path %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
                </li>
              </ul>
            </li>
        <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/component/_text_field.html.erb
<div class="form-group">
  <label><%= label_val %></label>
  <%= f.text_field n ,:class=>"form-control input-sm" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clube</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "component/menu" %>

<%= yield %>

</body>
</html>

app/views/layouts/devise_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clube | Login </title>
  <%= stylesheet_link_tag    "deviseapplication", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "deviseapplication", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "component/menu" %>

<%= yield %>

</body>
</html>

app/views/profile_images/_form.html.erb
<%= form_for(@profile_image) do |f| %>
  <% if @profile_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile_image.errors.count, "error") %> prohibited this profile_image from being saved:</h2>

      <ul>
      <% @profile_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profile_images/edit.html.erb
<h1>Editing profile_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile_image %> |
<%= link_to 'Back', profile_images_path %>

app/views/profile_images/index.html.erb
<h1>Listing profile_images</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profile_images.each do |profile_image| %>
      <tr>
        <td><%= profile_image.image %></td>
        <td><%= link_to 'Show', profile_image %></td>
        <td><%= link_to 'Edit', edit_profile_image_path(profile_image) %></td>
        <td><%= link_to 'Destroy', profile_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile image', new_profile_image_path %>

app/views/profile_images/new.html.erb
<h1>New profile_image</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_images_path %>

app/views/profile_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @profile_image.image %>
</p>

<%= link_to 'Edit', edit_profile_image_path(@profile_image) %> |
<%= link_to 'Back', profile_images_path %>

app/views/qualifications/_form.html.erb
<%= form_for(@qualification) do |f| %>
  <% if @qualification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualification.errors.count, "error") %> prohibited this qualification from being saved:</h2>

      <ul>
      <% @qualification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qualifications/edit.html.erb
<h1>Editing qualification</h1>

<%= render 'form' %>

<%= link_to 'Show', @qualification %> |
<%= link_to 'Back', qualifications_path %>

app/views/qualifications/index.html.erb
<h1>Listing qualifications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @qualifications.each do |qualification| %>
      <tr>
        <td><%= qualification.name %></td>
        <td><%= link_to 'Show', qualification %></td>
        <td><%= link_to 'Edit', edit_qualification_path(qualification) %></td>
        <td><%= link_to 'Destroy', qualification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualification', new_qualification_path %>

app/views/qualifications/new.html.erb
<h1>New qualification</h1>

<%= render 'form' %>

<%= link_to 'Back', qualifications_path %>

app/views/qualifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @qualification.name %>
</p>

<%= link_to 'Edit', edit_qualification_path(@qualification) %> |
<%= link_to 'Back', qualifications_path %>

app/views/users/index.html.erb
<div class="container">
    <table class="table">
      <thead>
          <th>Name</th>
          <th>Qualification</th>
      </thead>
      <tbody>
      <% @users.each do |u| %>
          <tr>
            <td><%= u.profile.first_name %></td>
            <td><%= get_qualification(u.profile.education) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
</div>

app/views/users/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="well well-sm">
        <div class="media">
          <a class="pull-left" href="#">
            <!--image_tag @user.profile_images[0].image_url(:profile),:class=>"thumbnail" -->
            <%= render :partial => "component/image_slider" %>
          </a>
          <div class="media-body" style="padding-left:10px;">
            <h4 class="media-heading">
              <%= @user.profile.first_name.to_s.capitalize %> <%= @user.profile.last_name.to_s.capitalize %>
            </h4>
            <p><span class="label label-info">5 photos</span> <span class="label label-warning">150 Likes</span></p>
            <p>
              <a href="#" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-comment"></span> Message</a>
              <a href="#" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-heart"></span> Favorite</a>
            </p>
            <div style="height:15px;"></div>
            <div class="col-md-6" style="padding-left:0px;">
              <table class="table table-bordered">
                <tr>
                  <td colspan="2"><b>User Infomation</b></td>
                </tr>
                <tr>
                  <td>Gender</td>
                  <td><%= @user.profile.gender %></td>
                </tr>
                <tr>
                  <td>Date of Birth</td>
                  <td><%= @user.profile.date_of_birth %></td>
                </tr>
                <tr>
                  <td>Qualification</td>
                  <td><%= get_qualification(@user.profile.education) %></td>
                </tr>
                <tr>
                  <td>Annual Income</td>
                  <td><%= @user.profile.income %></td>
                </tr>
                <tr>
                  <td>Email</td>
                  <td><%= @user.email %></td>
                </tr>
                <tr>
                  <td>Contact No</td>
                  <td>
                    <%= @user.profile.contact1 %>
                    <% if !@user.profile.contact2.nil? && !@user.profile.contact2.blank? %>
                        , <%= @user.profile.contact2 %>
                    <% end %>
                  </td>
                </tr>
              </table>
            </div>
            <div class="col-md-6">
              <table class="table table-bordered">
                <tr>
                  <td colspan="2"><b>Family Infomation</b></td>
                </tr>
                <tr>
                  <td>Father Name</td>
                  <td><%= @user.famailyinfo.father_name %></td>
                </tr>
                <tr>
                  <td>Father Occupation</td>
                  <td><%= @user.famailyinfo.father_occupation %></td>
                </tr>
                <tr>
                  <td>Mother Name</td>
                  <td><%= @user.famailyinfo.monther %></td>
                </tr>
                <tr>
                  <td>Mother Occupation</td>
                  <td><%= @user.famailyinfo.mother_occupation  %></td>
                </tr>
                <tr>
                  <td>Contact No</td>
                  <td>
                    <%= @user.famailyinfo.contact1 %>
                    <% if !@user.famailyinfo.contact2.nil? && !@user.famailyinfo.contact2.blank? %>
                        , <%= @user.famailyinfo.contact2 %>
                    <% end %>
                  </td>
                </tr>
              </table>
            </div>
            <p>

            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="well well-sm">
        <div class="media">
          <div class="media-body" style="padding-left:10px;">
            <div style="height:15px;"></div>
            <p>
            <table class="table table-bordered">
              <tr>
                <td><b>Address Infomation</b></td>
              </tr>
              <tr>
                <td>
                  <%= @user.addresses[0].address1 %><br>
                  <%= @user.addresses[0].address2 %><br>
                  <%= @user.addresses[0].city %><br>
                  <%= @user.addresses[0].state %><br>
                  <%= @user.addresses[0].country %><br>
                  <%= @user.addresses[0].zip_code %><br>
                </td>
              </tr>
            </table>
            </p>
            <p>

            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
    jssor_1_slider_init();
</script>